./pair_and_insert.sh ../parents/0/dna137 ../parents/1/
./pair_and_insert.sh ../parents/0/dna157 ../parents/1/
./pair_and_insert.sh ../parents/0/dna170 ../parents/1/
./pair_and_insert.sh ../parents/0/dna177 ../parents/1/
./pair_and_insert.sh ../parents/0/dna179 ../parents/1/
./pair_and_insert.sh ../parents/0/dna186 ../parents/1/
./pair_and_insert.sh ../parents/0/dna193 ../parents/1/
./pair_and_insert.sh ../parents/0/dna203 ../parents/1/
./pair_and_insert.sh ../parents/0/dna204 ../parents/1/
./pair_and_insert.sh ../parents/0/dna209 ../parents/1/
./pair_and_insert.sh ../parents/0/dna218 ../parents/1/
./pair_and_insert.sh ../parents/0/dna221 ../parents/1/
./pair_and_insert.sh ../parents/0/dna230 ../parents/1/
./pair_and_insert.sh ../parents/0/dna232 ../parents/1/
./pair_and_insert.sh ../parents/0/dna24 ../parents/1/
./pair_and_insert.sh ../parents/0/dna240 ../parents/1/
./pair_and_insert.sh ../parents/0/dna241 ../parents/1/
./pair_and_insert.sh ../parents/0/dna255 ../parents/1/
./pair_and_insert.sh ../parents/0/dna257 ../parents/1/
./pair_and_insert.sh ../parents/0/dna26 ../parents/1/
./pair_and_insert.sh ../parents/0/dna267 ../parents/1/
./pair_and_insert.sh ../parents/0/dna277 ../parents/1/
./pair_and_insert.sh ../parents/0/dna278 ../parents/1/
./pair_and_insert.sh ../parents/0/dna284 ../parents/1/
./pair_and_insert.sh ../parents/0/dna290 ../parents/1/
./pair_and_insert.sh ../parents/0/dna291 ../parents/1/
./pair_and_insert.sh ../parents/0/dna293 ../parents/1/
./pair_and_insert.sh ../parents/0/dna297 ../parents/1/
./pair_and_insert.sh ../parents/0/dna305 ../parents/1/
./pair_and_insert.sh ../parents/0/dna329 ../parents/1/
./pair_and_insert.sh ../parents/0/dna333 ../parents/1/
./pair_and_insert.sh ../parents/0/dna36 ../parents/1/
./pair_and_insert.sh ../parents/0/dna38 ../parents/1/
./pair_and_insert.sh ../parents/0/dna43 ../parents/1/
./pair_and_insert.sh ../parents/0/dna45 ../parents/1/
./pair_and_insert.sh ../parents/0/dna51 ../parents/1/
./pair_and_insert.sh ../parents/0/dna515 ../parents/1/
./pair_and_insert.sh ../parents/0/dna53 ../parents/1/
./pair_and_insert.sh ../parents/0/dna55 ../parents/1/
./pair_and_insert.sh ../parents/0/dna57 ../parents/1/
./pair_and_insert.sh ../parents/0/dna62 ../parents/1/
./pair_and_insert.sh ../parents/0/dna655 ../parents/1/
./pair_and_insert.sh ../parents/0/dna658 ../parents/1/
./pair_and_insert.sh ../parents/0/dna697 ../parents/1/
./pair_and_insert.sh ../parents/0/dna787 ../parents/1/
./pair_and_insert.sh ../parents/0/dna81 ../parents/1/
./pair_and_insert.sh ../parents/0/dna83 ../parents/1/
./pair_and_insert.sh ../parents/0/dna937 ../parents/1/
./pair_and_insert.sh ../parents/0/dna97 ../parents/1/
./pair_and_insert.sh ../parents/0/dna979 ../parents/1/
