./pair_and_insert.sh ../parents/0/dna107 ../parents/1/
./pair_and_insert.sh ../parents/0/dna112 ../parents/1/
./pair_and_insert.sh ../parents/0/dna115 ../parents/1/
./pair_and_insert.sh ../parents/0/dna12 ../parents/1/
./pair_and_insert.sh ../parents/0/dna158 ../parents/1/
./pair_and_insert.sh ../parents/0/dna168 ../parents/1/
./pair_and_insert.sh ../parents/0/dna171 ../parents/1/
./pair_and_insert.sh ../parents/0/dna181 ../parents/1/
./pair_and_insert.sh ../parents/0/dna185 ../parents/1/
./pair_and_insert.sh ../parents/0/dna211 ../parents/1/
./pair_and_insert.sh ../parents/0/dna23 ../parents/1/
./pair_and_insert.sh ../parents/0/dna25 ../parents/1/
./pair_and_insert.sh ../parents/0/dna257 ../parents/1/
./pair_and_insert.sh ../parents/0/dna262 ../parents/1/
./pair_and_insert.sh ../parents/0/dna282 ../parents/1/
./pair_and_insert.sh ../parents/0/dna300 ../parents/1/
./pair_and_insert.sh ../parents/0/dna313 ../parents/1/
./pair_and_insert.sh ../parents/0/dna314 ../parents/1/
./pair_and_insert.sh ../parents/0/dna317 ../parents/1/
./pair_and_insert.sh ../parents/0/dna321 ../parents/1/
./pair_and_insert.sh ../parents/0/dna341 ../parents/1/
./pair_and_insert.sh ../parents/0/dna344 ../parents/1/
./pair_and_insert.sh ../parents/0/dna404 ../parents/1/
./pair_and_insert.sh ../parents/0/dna408 ../parents/1/
./pair_and_insert.sh ../parents/0/dna415 ../parents/1/
./pair_and_insert.sh ../parents/0/dna43 ../parents/1/
./pair_and_insert.sh ../parents/0/dna435 ../parents/1/
./pair_and_insert.sh ../parents/0/dna440 ../parents/1/
./pair_and_insert.sh ../parents/0/dna458 ../parents/1/
./pair_and_insert.sh ../parents/0/dna472 ../parents/1/
./pair_and_insert.sh ../parents/0/dna483 ../parents/1/
./pair_and_insert.sh ../parents/0/dna493 ../parents/1/
./pair_and_insert.sh ../parents/0/dna498 ../parents/1/
./pair_and_insert.sh ../parents/0/dna505 ../parents/1/
./pair_and_insert.sh ../parents/0/dna51 ../parents/1/
./pair_and_insert.sh ../parents/0/dna511 ../parents/1/
./pair_and_insert.sh ../parents/0/dna516 ../parents/1/
./pair_and_insert.sh ../parents/0/dna549 ../parents/1/
./pair_and_insert.sh ../parents/0/dna565 ../parents/1/
./pair_and_insert.sh ../parents/0/dna634 ../parents/1/
./pair_and_insert.sh ../parents/0/dna642 ../parents/1/
./pair_and_insert.sh ../parents/0/dna81 ../parents/1/
./pair_and_insert.sh ../parents/0/dna838 ../parents/1/
./pair_and_insert.sh ../parents/0/dna867 ../parents/1/
./pair_and_insert.sh ../parents/0/dna879 ../parents/1/
./pair_and_insert.sh ../parents/0/dna91 ../parents/1/
./pair_and_insert.sh ../parents/0/dna94 ../parents/1/
./pair_and_insert.sh ../parents/0/dna97 ../parents/1/
./pair_and_insert.sh ../parents/0/dna99 ../parents/1/
./pair_and_insert.sh ../parents/0/dna994 ../parents/1/
