java -jar ../../../jars/pairer.jar ../parents/0/+dna101
java -jar ../../../jars/pairer.jar ../parents/0/+dna127
java -jar ../../../jars/pairer.jar ../parents/0/+dna135
java -jar ../../../jars/pairer.jar ../parents/0/+dna143
java -jar ../../../jars/pairer.jar ../parents/0/+dna175
java -jar ../../../jars/pairer.jar ../parents/0/+dna204
java -jar ../../../jars/pairer.jar ../parents/0/+dna218
java -jar ../../../jars/pairer.jar ../parents/0/+dna24
java -jar ../../../jars/pairer.jar ../parents/0/+dna244
java -jar ../../../jars/pairer.jar ../parents/0/+dna264
java -jar ../../../jars/pairer.jar ../parents/0/+dna288
java -jar ../../../jars/pairer.jar ../parents/0/+dna293
java -jar ../../../jars/pairer.jar ../parents/0/+dna339
java -jar ../../../jars/pairer.jar ../parents/0/+dna346
java -jar ../../../jars/pairer.jar ../parents/0/+dna375
java -jar ../../../jars/pairer.jar ../parents/0/+dna377
java -jar ../../../jars/pairer.jar ../parents/0/+dna424
java -jar ../../../jars/pairer.jar ../parents/0/+dna448
java -jar ../../../jars/pairer.jar ../parents/0/+dna552
java -jar ../../../jars/pairer.jar ../parents/0/+dna556
java -jar ../../../jars/pairer.jar ../parents/0/+dna563
java -jar ../../../jars/pairer.jar ../parents/0/+dna580
java -jar ../../../jars/pairer.jar ../parents/0/+dna582
java -jar ../../../jars/pairer.jar ../parents/0/+dna583
java -jar ../../../jars/pairer.jar ../parents/0/+dna589
java -jar ../../../jars/pairer.jar ../parents/0/+dna605
java -jar ../../../jars/pairer.jar ../parents/0/+dna613
java -jar ../../../jars/pairer.jar ../parents/0/+dna615
java -jar ../../../jars/pairer.jar ../parents/0/+dna637
java -jar ../../../jars/pairer.jar ../parents/0/+dna64
java -jar ../../../jars/pairer.jar ../parents/0/+dna653
java -jar ../../../jars/pairer.jar ../parents/0/+dna66
java -jar ../../../jars/pairer.jar ../parents/0/+dna668
java -jar ../../../jars/pairer.jar ../parents/0/+dna703
java -jar ../../../jars/pairer.jar ../parents/0/+dna706
java -jar ../../../jars/pairer.jar ../parents/0/+dna722
java -jar ../../../jars/pairer.jar ../parents/0/+dna753
java -jar ../../../jars/pairer.jar ../parents/0/+dna766
java -jar ../../../jars/pairer.jar ../parents/0/+dna772
java -jar ../../../jars/pairer.jar ../parents/0/+dna812
java -jar ../../../jars/pairer.jar ../parents/0/+dna816
java -jar ../../../jars/pairer.jar ../parents/0/+dna847
java -jar ../../../jars/pairer.jar ../parents/0/+dna869
java -jar ../../../jars/pairer.jar ../parents/0/+dna885
java -jar ../../../jars/pairer.jar ../parents/0/+dna886
java -jar ../../../jars/pairer.jar ../parents/0/+dna892
java -jar ../../../jars/pairer.jar ../parents/0/+dna904
java -jar ../../../jars/pairer.jar ../parents/0/+dna913
java -jar ../../../jars/pairer.jar ../parents/0/+dna957
java -jar ../../../jars/pairer.jar ../parents/0/+dna970
