./pair_and_insert.sh ../parents/0/+dna107
./pair_and_insert.sh ../parents/0/+dna112
./pair_and_insert.sh ../parents/0/+dna115
./pair_and_insert.sh ../parents/0/+dna12
./pair_and_insert.sh ../parents/0/+dna158
./pair_and_insert.sh ../parents/0/+dna168
./pair_and_insert.sh ../parents/0/+dna171
./pair_and_insert.sh ../parents/0/+dna181
./pair_and_insert.sh ../parents/0/+dna185
./pair_and_insert.sh ../parents/0/+dna211
./pair_and_insert.sh ../parents/0/+dna23
./pair_and_insert.sh ../parents/0/+dna25
./pair_and_insert.sh ../parents/0/+dna257
./pair_and_insert.sh ../parents/0/+dna262
./pair_and_insert.sh ../parents/0/+dna282
./pair_and_insert.sh ../parents/0/+dna300
./pair_and_insert.sh ../parents/0/+dna313
./pair_and_insert.sh ../parents/0/+dna314
./pair_and_insert.sh ../parents/0/+dna317
./pair_and_insert.sh ../parents/0/+dna321
./pair_and_insert.sh ../parents/0/+dna341
./pair_and_insert.sh ../parents/0/+dna344
./pair_and_insert.sh ../parents/0/+dna404
./pair_and_insert.sh ../parents/0/+dna408
./pair_and_insert.sh ../parents/0/+dna415
./pair_and_insert.sh ../parents/0/+dna43
./pair_and_insert.sh ../parents/0/+dna435
./pair_and_insert.sh ../parents/0/+dna440
./pair_and_insert.sh ../parents/0/+dna458
./pair_and_insert.sh ../parents/0/+dna472
./pair_and_insert.sh ../parents/0/+dna483
./pair_and_insert.sh ../parents/0/+dna493
./pair_and_insert.sh ../parents/0/+dna498
./pair_and_insert.sh ../parents/0/+dna505
./pair_and_insert.sh ../parents/0/+dna51
./pair_and_insert.sh ../parents/0/+dna511
./pair_and_insert.sh ../parents/0/+dna516
./pair_and_insert.sh ../parents/0/+dna549
./pair_and_insert.sh ../parents/0/+dna565
./pair_and_insert.sh ../parents/0/+dna634
./pair_and_insert.sh ../parents/0/+dna642
./pair_and_insert.sh ../parents/0/+dna81
./pair_and_insert.sh ../parents/0/+dna838
./pair_and_insert.sh ../parents/0/+dna867
./pair_and_insert.sh ../parents/0/+dna879
./pair_and_insert.sh ../parents/0/+dna91
./pair_and_insert.sh ../parents/0/+dna94
./pair_and_insert.sh ../parents/0/+dna97
./pair_and_insert.sh ../parents/0/+dna99
./pair_and_insert.sh ../parents/0/+dna994
