./pair_and_insert.sh ../parents/0/+dna137
./pair_and_insert.sh ../parents/0/+dna157
./pair_and_insert.sh ../parents/0/+dna170
./pair_and_insert.sh ../parents/0/+dna177
./pair_and_insert.sh ../parents/0/+dna179
./pair_and_insert.sh ../parents/0/+dna186
./pair_and_insert.sh ../parents/0/+dna193
./pair_and_insert.sh ../parents/0/+dna203
./pair_and_insert.sh ../parents/0/+dna204
./pair_and_insert.sh ../parents/0/+dna209
./pair_and_insert.sh ../parents/0/+dna218
./pair_and_insert.sh ../parents/0/+dna221
./pair_and_insert.sh ../parents/0/+dna230
./pair_and_insert.sh ../parents/0/+dna232
./pair_and_insert.sh ../parents/0/+dna24
./pair_and_insert.sh ../parents/0/+dna240
./pair_and_insert.sh ../parents/0/+dna241
./pair_and_insert.sh ../parents/0/+dna255
./pair_and_insert.sh ../parents/0/+dna257
./pair_and_insert.sh ../parents/0/+dna26
./pair_and_insert.sh ../parents/0/+dna267
./pair_and_insert.sh ../parents/0/+dna277
./pair_and_insert.sh ../parents/0/+dna278
./pair_and_insert.sh ../parents/0/+dna284
./pair_and_insert.sh ../parents/0/+dna290
./pair_and_insert.sh ../parents/0/+dna291
./pair_and_insert.sh ../parents/0/+dna293
./pair_and_insert.sh ../parents/0/+dna297
./pair_and_insert.sh ../parents/0/+dna305
./pair_and_insert.sh ../parents/0/+dna329
./pair_and_insert.sh ../parents/0/+dna333
./pair_and_insert.sh ../parents/0/+dna36
./pair_and_insert.sh ../parents/0/+dna38
./pair_and_insert.sh ../parents/0/+dna43
./pair_and_insert.sh ../parents/0/+dna45
./pair_and_insert.sh ../parents/0/+dna51
./pair_and_insert.sh ../parents/0/+dna515
./pair_and_insert.sh ../parents/0/+dna53
./pair_and_insert.sh ../parents/0/+dna55
./pair_and_insert.sh ../parents/0/+dna57
./pair_and_insert.sh ../parents/0/+dna62
./pair_and_insert.sh ../parents/0/+dna655
./pair_and_insert.sh ../parents/0/+dna658
./pair_and_insert.sh ../parents/0/+dna697
./pair_and_insert.sh ../parents/0/+dna787
./pair_and_insert.sh ../parents/0/+dna81
./pair_and_insert.sh ../parents/0/+dna83
./pair_and_insert.sh ../parents/0/+dna937
./pair_and_insert.sh ../parents/0/+dna97
./pair_and_insert.sh ../parents/0/+dna979
