echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
echo "./pair_and_insert.sh ../parents/0/" >> pair_jars.txt
